<a href="https://colab.research.google.com/github/simaryadav/learning_roadmap/blob/main/Encoding_to_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
### Vocabulary size
voc_size=500

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[284, 462, 488, 197], [284, 462, 488, 163], [284, 227, 488, 315], [396, 45, 357, 184, 392], [396, 45, 357, 184, 324], [73, 284, 302, 488, 8], [229, 144, 370, 184]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 284 462 488 197]
 [  0   0   0   0 284 462 488 163]
 [  0   0   0   0 284 227 488 315]
 [  0   0   0 396  45 357 184 392]
 [  0   0   0 396  45 357 184 324]
 [  0   0   0  73 284 302 488   8]
 [  0   0   0   0 229 144 370 184]]


In [9]:
## 10 feature dimesnions
dim=10


In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (8, 10)                     │           5,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 284, 462, 488, 197], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 223ms/step


array([[ 0.02580944,  0.03687337, -0.02617524,  0.02914527, -0.00855248,
        -0.0198236 ,  0.02495774, -0.03772832,  0.01522917,  0.00379638],
       [ 0.02580944,  0.03687337, -0.02617524,  0.02914527, -0.00855248,
        -0.0198236 ,  0.02495774, -0.03772832,  0.01522917,  0.00379638],
       [ 0.02580944,  0.03687337, -0.02617524,  0.02914527, -0.00855248,
        -0.0198236 ,  0.02495774, -0.03772832,  0.01522917,  0.00379638],
       [ 0.02580944,  0.03687337, -0.02617524,  0.02914527, -0.00855248,
        -0.0198236 ,  0.02495774, -0.03772832,  0.01522917,  0.00379638],
       [ 0.00184084, -0.01052731, -0.04779366, -0.01354134,  0.01599376,
         0.0019397 , -0.02544384, -0.02885542, -0.04053776,  0.0375835 ],
       [ 0.03068698,  0.00657115, -0.0020986 ,  0.02532296,  0.02126448,
         0.00805527,  0.00389618,  0.02225479, -0.01405655, -0.04400382],
       [ 0.02678451, -0.02063924,  0.00454891,  0.00611011, -0.01948152,
        -0.01164105, -0.03727443, -0.04595276

In [16]:
print(model.predict(embedded_docs))

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 284, 462, 488, 197], dtype=int32)

In [21]:

print(model.predict(embedded_docs)[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]